"""added a project_statement (v2)

Revision ID: 3484818923b7
Revises: 2e1eeffc63c2
Create Date: 2023-10-17 09:42:25.606150

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '3484818923b7'
down_revision = '2e1eeffc63c2'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('project', schema=None) as batch_op:
        batch_op.add_column(sa.Column('problem_statement', sa.Text(), nullable=True))

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('project', schema=None) as batch_op:
        batch_op.drop_column('problem_statement')

    # ### end Alembic commands ###
