"""added is_active to authenticate users

Revision ID: 531b88a28a85
Revises: a692c60a2c1f
Create Date: 2024-02-07 18:20:25.478373

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '531b88a28a85'
down_revision = 'a692c60a2c1f'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('user', schema=None) as batch_op:
        # Add the is_active column with a default value of True for existing rows
        batch_op.add_column(sa.Column('is_active', sa.Boolean(), nullable=False, server_default='true'))
    
    # If you need to remove the server_default after applying it to existing rows
    # You might need to use a separate operation outside of the batch operation, like so:
    with op.batch_alter_table('user', schema=None) as batch_op:
        batch_op.alter_column('is_active',
                              existing_type=sa.Boolean(),
                              server_default=None)
        # This step is optional and only needed if you don't want a server_default on the column

    # Drop column example remains unchanged
    with op.batch_alter_table('user', schema=None) as batch_op:
        batch_op.drop_column('last_page')


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('user', schema=None) as batch_op:
        batch_op.add_column(sa.Column('last_page', sa.VARCHAR(length=150), autoincrement=False, nullable=True))
        batch_op.drop_column('is_active')

    # ### end Alembic commands ###
