"""added client, difficulty, completionRate, coverImage, and industry fields to Data Models. Also updated CMS to include dropdowns for client, difficulty.

Revision ID: a47d775aca5b
Revises: e1de77e3c2f8
Create Date: 2024-01-25 19:01:17.249225

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'a47d775aca5b'
down_revision = 'e1de77e3c2f8'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('project_template', schema=None) as batch_op:
        batch_op.add_column(sa.Column('coverImage', sa.String(length=1500), nullable=True))
        batch_op.add_column(sa.Column('industry', sa.String(length=500), nullable=True))
        batch_op.add_column(sa.Column('difficulty', sa.String(length=150), nullable=True))
        batch_op.add_column(sa.Column('client', sa.String(length=1500), nullable=True))

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('project_template', schema=None) as batch_op:
        batch_op.drop_column('client')
        batch_op.drop_column('difficulty')
        batch_op.drop_column('industry')
        batch_op.drop_column('coverImage')

    # ### end Alembic commands ###
