"""Upgraded Link column to support Text

Revision ID: a8eb0958016d
Revises: ab69762ea7b4
Create Date: 2023-11-11 19:13:16.831875

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'a8eb0958016d'
down_revision = 'ab69762ea7b4'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('project_template', schema=None) as batch_op:
        batch_op.alter_column('companyOverview',
               existing_type=sa.VARCHAR(length=1000),
               type_=sa.String(length=1500),
               existing_nullable=True)
        batch_op.alter_column('objective',
               existing_type=sa.VARCHAR(length=1000),
               type_=sa.String(length=1500),
               existing_nullable=True)

    with op.batch_alter_table('task', schema=None) as batch_op:
        batch_op.alter_column('link',
               existing_type=sa.VARCHAR(length=1500),
               type_=sa.Text(),
               existing_nullable=True)

    with op.batch_alter_table('task_template', schema=None) as batch_op:
        batch_op.alter_column('description',
               existing_type=sa.VARCHAR(length=500),
               type_=sa.Text(),
               existing_nullable=False)

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('task_template', schema=None) as batch_op:
        batch_op.alter_column('description',
               existing_type=sa.Text(),
               type_=sa.VARCHAR(length=500),
               existing_nullable=False)

    with op.batch_alter_table('task', schema=None) as batch_op:
        batch_op.alter_column('link',
               existing_type=sa.Text(),
               type_=sa.VARCHAR(length=1500),
               existing_nullable=True)

    with op.batch_alter_table('project_template', schema=None) as batch_op:
        batch_op.alter_column('objective',
               existing_type=sa.String(length=1500),
               type_=sa.VARCHAR(length=1000),
               existing_nullable=True)
        batch_op.alter_column('companyOverview',
               existing_type=sa.String(length=1500),
               type_=sa.VARCHAR(length=1000),
               existing_nullable=True)

    # ### end Alembic commands ###
