"""is_public to Project Model

Revision ID: ab69762ea7b4
Revises: 3484818923b7
Create Date: 2023-11-09 19:34:53.050499

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'ab69762ea7b4'
down_revision = '3484818923b7'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('project', sa.Column('is_public', sa.Boolean(), nullable=False, server_default=sa.text('False')))
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('project', schema=None) as batch_op:
        batch_op.drop_column('is_public')

    # ### end Alembic commands ###
