"""removed summary link from Task Model

Revision ID: e1de77e3c2f8
Revises: e9b2e67db774
Create Date: 2024-01-16 11:00:42.267588

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'e1de77e3c2f8'
down_revision = 'e9b2e67db774'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('task', schema=None) as batch_op:
        batch_op.drop_column('summary_link')

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('task', schema=None) as batch_op:
        batch_op.add_column(sa.Column('summary_link', sa.TEXT(), autoincrement=False, nullable=True))

    # ### end Alembic commands ###
