"""added a summary_link field

Revision ID: e9b2e67db774
Revises: c7e8beb3ce4d
Create Date: 2023-12-08 14:10:24.152420

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'e9b2e67db774'
down_revision = 'c7e8beb3ce4d'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('task', schema=None) as batch_op:
        batch_op.add_column(sa.Column('summary_link', sa.Text(), nullable=True))

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('task', schema=None) as batch_op:
        batch_op.drop_column('summary_link')

    # ### end Alembic commands ###
